### ISSUE TITLE
DivertAsync receive problem

### ISSUE THREAD

**Issue by TheGreatFred** [TechnikEmpire/Divert.Net#14]
Hi there,

Not sure if I'm doing this right but I tried the following:

```C#
while (!signalCancel)
{
	DivertAsyncResult asyncReceive = new DivertAsyncResult();
	bool got_packet = filter.ReceiveAsync(raw_packet, addr, ref raw_packet_len, asyncReceive);
	while (!got_packet)
		got_packet = asyncReceive.Get(1000);
        //do stuff...
```

Which seems to work for a while but then I get a SEHException (External component has thrown an exception) from here:

```C++
bool DivertHandle::Close()
{
	if (Valid)
	{
		if (m_fromWinDivert)
		{
			return WinDivertClose(m_handle) == 1;
		}
		else
		{
			return CloseHandle(m_handle) != 0;   //     <= crashes here
		}				
	}
	else
	{
		return false;
	}
}
```

I'll try and trace out exactly which Divert.NET call throws the exception... just wondering why DivertHandle.Close() is getting called?!

Hopefully it's a case of "you're doing it wrong!" :)

Regards,

Andy

**Comment by TechnikEmpire** [comment]
@AndyBeamish 

I'll have to look more closely but you shouldn't be calling `while(!got_packet)`, it should simply be `if(!got_packet)`. That'll probably get you into a deadlock, or at the very least get you continuously trying to receive a packet that is just plain lost (dropped). However, this may still also be a bug where this incorrect usage is causing an attempted double free of a handle.

The handle is being freed upon failure. There are two handles used here. The first is a handle to the divert library, the second is a WinAPI overlapped handle, which is used to fetch the overlapped IO result when it's not immediately available after the initial call to the async receive method. Will investigate this, but try changing your logic to remove the while condition on the original async read failure as I mention above.

**Comment by TechnikEmpire** [comment]
@AndyBeamish There was indeed a bug, but my remarks regarding your use of the while loop when the packet isn't immediately available still stand. Bug is fixed. Thanks for the report.

**Comment by TechnikEmpire** [comment]
Also @AndyBeamish keep in mind that there is a Pinvoke version [here](https://github.com/TechnikEmpire/DivertPInvoke) if that suits you better, although its lacking quite a few frills such as the ability to get the process name behind a packet flow, for example.

**Comment by TheGreatFred** [comment]
Hmm, so are you saying after my asyncReceive either hands back a packet or errors (no data) I should then look back to a new ReceiveAsync? I supposed I should have seen that coming, comparing to the blocking Receive version.

Glad I could help find a bug though! I did have a quick look at PInvoke but apart from using the structures for packet templates the rest looked a bit too scary! The /unsafe flag is not one to click on casually :)

**Comment by TechnikEmpire** [comment]
@AndyBeamish no, I'm saying that if the initial call to the async read method returns `false`, and [`Marshal.GetLastWin32Error()`](http://stackoverflow.com/questions/17918266/winapi-getlasterror-vs-marshal-getlastwin32error/17918729#17918729) is equal to `ERROR_IO_PENDING`, which is [defined as int 997](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx), then you call `asyncReceive.Get(TIMEOUT_MILLISECONDS)`.

If the `asyncReceive.Get(TIMEOUT_MILLISECONDS)` function also returns false, then the capture failed entirely. If the initial async receive method returns false and `Marshal.GetLastWin32Error()` is NOT equal to 997, then the packet capture failed entirely also. You'd have to look up the code you get from `Marshal.GetLastWin32Error()` to find out why.

You've almost got it right, just don't use a while loop. Also, you need to check `Marshal.GetLastWin32Error()` obviously as mentioned.

As far as `/unsafe` flag, I personally find it ridiculous. It reminds me of Adobe trying to hold every flash developer's hand and prevent them from having real access to hardware or true worker threads because they didn't want people causing deadlocks or crashes on their precious platform. "Safe" CLR code is perfectly capable of pointer arithmetic that can kill a whole basket of kittens. Microsoft almost turned the .NET platform into what Fisher Price tools are to Makita power tools by doing this. But, that's enough ranting from me.

Check the WinDivert tests code [here](https://github.com/basil00/Divert/blob/master/test/test.c#L434) to see how the author uses the async functions (the same ones you're using under the sweet C# syntax). Also, you can always read the official [WinDivert](https://reqrypt.org/windivert-doc-v1.2.html) docs. The function names are a little different in this wrapper, but the struct/class names/functionality is the same.

**Comment by TheGreatFred** [comment]
Thank you so much for the reply! Starting to make a lot more sense. I'm using the blocking version of **Read()** at the moment and there's a bit of a "run it on a thread, kill it with **Thread.Abort()**" cheekiness when my program exits... and there's me going "oh noes, /unsafe scary!" ;D

One, unrelated observation: it took me quite a while to wrap my head around reconstructing packets. **ParsePacket()** does a great job of breaking things down into headers but going the other way you just get a small assist with **CalcChecksums()** :(

Okay, maybe this is something to go back to the original WinDivert author(s) with but with the **webfilter.c** example it all looks so easy: lob a pointer at your packet structure (it instantly _is_ a stream of bytes) swap to network byte order here and there, done!

That doesn't really suit the style of .NET: too much **[LayoutKind.Sequential]** and **Marshal.StructureToPtr()**. Don't get me wrong, it's great to be allowed to have these things and not go all "Fisher Price" but it's nails down a chalk board to me!

I'm gonna look over my code to see about swapping out **Read()** for **ReadAsync()** so I might contemplate how a theoretical **ConstructPacket()** might work :)
